apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubecost-custom-scc
allowHostNetwork: true
allowHostPorts: true
allowPrivilegedContainer: true
volumes:
- hostPath
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:kubecost:kubecost-cost-analyzer
